---
version: "3.8"

secrets:
  code_password:
    file: code.password

networks:
  swagnet:
    external: true

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    secrets:
      - code_password
    extra_hosts:
      abyss: '192.168.1.2'
    environment:
      - PUID=${U_UID}
      - PGID=${U_GID}
      - TZ=Europe/Paris
      - FILE__PASSWORD=/run/secrets/code_password
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./data/config:/config
      - ../../.:/config/workspace
    # ports:
    #   - 8443:8443
    networks:
      - swagnet
    restart: unless-stopped
