---
version: "3.8"

networks:
  infra:
    external: true

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - SIGNUPS_ALLOWED=false
    volumes:
      - ./vw-data:/data
    networks:
      - infra
    restart: always
