---
version: "3.8"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${U_UID}
      - PGID=${U_GID}
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
    ports:
      - 8006:80
      - 406:443
    restart: unless-stopped
