version: "3.8"

networks:
  swagnet:
    external: true

services:
  web:
    image: tailscale/tailscale:latest
    command: "sh -c 'tailscale web --listen 0.0.0.0:8240 & exec tailscaled --tun=userspace-networking'"
    ports:
      - 8240:8240
    volumes:
      - ./data:/var/lib
    networks:
      - swagnet
    stop_grace_period: 1m
    restart: on-failure
