---
version: "3.8"

networks:
  swagnet:
    external: true

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - 8000:8000
      - 9443:9443
    #   - 9000:9000
    networks:
      - swagnet
    restart: always

volumes:
  portainer_data:
    driver: local
