---
version: "3.8"

networks:
  infra:
    external: true

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${U_UID}
      - PGID=${U_GID}
      - TZ=Europe/Paris
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      # - USER=ppouloup #optional
      # - PASS=ppouloup #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT=peerport #optional
      # - HOST_WHITELIST=dnsname list #optional
    volumes:
      - ./data/config:/config
      - ./data/torrents:/watch
      - /nas/Films:/downloads
    ports:
      # - 9091:9091 # UI
      - 51413:51413
      - 51413:51413/udp
    networks:
      - infra
    restart: unless-stopped
