---
version: "3.8"

networks:
  infra:
    external: true

secrets:
  photoprism_password:
    file: photoprism.password

services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    # ports:
    #   - 2342:2342
    environment:
        PHOTOPRISM_SITE_URL: "https://photoprism.dune-local.duckdns.org"
        PHOTOPRISM_SITE_TITLE: "Home Photos"
        PHOTOPRISM_SITE_CAPTION: "Personal photo archives"
        PHOTOPRISM_ADMIN_PASSWORD: "photoprism"
        PHOTOPRISM_ORIGINALS_LIMIT: 100000
        PHOTOPRISM_HTTP_COMPRESSION: "gzip"
        PHOTOPRISM_DEBUG: "false"
        PHOTOPRISM_PUBLIC: "false"
        PHOTOPRISM_READONLY: "false"
        PHOTOPRISM_EXPERIMENTAL: "false"
        PHOTOPRISM_DISABLE_WEBDAV: "false"
        PHOTOPRISM_DISABLE_SETTINGS: "false"
        PHOTOPRISM_DISABLE_TENSORFLOW: "false"
        PHOTOPRISM_DARKTABLE_PRESETS: "false"
        PHOTOPRISM_DETECT_NSFW: "true"
        PHOTOPRISM_UPLOAD_NSFW: "true"
        PHOTOPRISM_DATABASE_DRIVER: "mysql"
        PHOTOPRISM_DATABASE_SERVER: "photoprism_db:3306"
        PHOTOPRISM_DATABASE_NAME: "photoprism"
        PHOTOPRISM_DATABASE_USER: "photoprism"
        PHOTOPRISM_DATABASE_PASSWORD: "photoprism"
        PHOTOPRISM_WORKERS: 3
    volumes:
      - ./photos:/photoprism/originals
      - ./storage:/photoprism/storage
      - ./import:/photoprism/import
    networks:
      - infra

  photoprism_db:
    image: mariadb:latest
    container_name: photoprism_db
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
    networks:
      - infra
    restart: unless-stopped
