---
version: "3.8"

networks:
  swagnet:
    external: true

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    environment:
      - NODE_ENV=production
      - UID=${U_UID}
      - GID=${U_GID}
    volumes:
      - ./data/config.yml:/app/public/conf.yml
    ports:
      - 4000:80
    # Configure healthchecks
    networks:
      - swagnet
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
